version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ./local.Dockerfile
    tty: true
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
  api:
    build: ./api
    command: npm run dev
    depends_on:
      - mongodb
    ports:
      - 3030:3030
    volumes:
      - ./api/src:/app/src
    environment:
      - NODE_ENV=docker
  mongodb:
    image: mongo:3.6.23
    ports:
      - 27017:27017
    volumes:
       - mongodb-data:/data/db
volumes:
  mongodb-data:
